service: my-gitLab-bot

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 128
    timeout: 6

functions:
    gitlab-bot:
        handler: index.handler
        events: 
          - http:
              path: /gitlab
              method: get
              cors: true
        